export const ABOUT_KEYWORDS = [
  "About ZenMart",
  "ZenMart mission",
  "ZenMart values",
  "ZenMart story",
  "About us",
  "Our journey",
  "Our team",
  "Company history",
  "ZenMart vision",
  "Why ZenMart",
  "Customer commitment",
  "Quality promise",
  "Our philosophy",
  "ZenMart difference",
  "Community engagement",
  "Customer focus",
  "Our passion",
  "Our purpose",
  "About our company",
  "ZenMart background",
];
